<?php

/**
 * @file
 * Contains block_exclude_pages.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * Provides help information for the block_exclude_pages module.
 */
function block_exclude_pages_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.block_exclude_pages':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module adds an exclude pages filter for blocks') . '</p>';
      $output .= '<p>'
        . t("<b>To exclude specific pages</b>, prefix the path with a '!'. Example excluded path <em class='placeholder'>!/user/jc</em>")
        . '<br><br>' . t("For More detail instructions to exclude pages visit: <a href='https://www.drupal.org/project/block_exclude_pages'>https://www.drupal.org/project/block_exclude_pages</a>")
        . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_condition_info_alter().
 *
 * Alters the condition definitions for the request path condition.
 */
function block_exclude_pages_condition_info_alter(array &$definitions) {
  if (isset($definitions['request_path']) && $definitions['request_path']['class'] === 'Drupal\\system\\Plugin\\Condition\\RequestPath') {
    $definitions['request_path']['class'] = 'Drupal\\block_exclude_pages\\Plugin\\Condition\\BlockExcludePagesRequestPath';
  }
}

/**
 * Debug function to test multiple paths.
 */
function block_exclude_pages_debug_trace($path_matcher, $exclude, $node_id, $path) {
  $debug_output = [];
  $paths = block_exclude_pages_debug_dummy_path();

  array_push($debug_output, "----------------------------- [ !" . $exclude . " ]------------------------------");

  foreach ($paths as $path) {
    if ($path_matcher->matchPath($node_id, $exclude) || $path_matcher->matchPath($path, $exclude)) {
      $debug_output[] = $exclude == $node_id
        ? "!" . $exclude . " : " . $node_id . " - BLOCKED <<<<<<<<<<<<<<<<<<<<<<<<<"
        : "!" . $exclude . " : " . $path . " - BLOCKED <<<<<<<<<<<<<<<<<<<<<<<<<";
    }
    else {
      $debug_output[] = "!" . $exclude . " : " . $path . " - PASSED";
    }
  }
  return $debug_output;
}

/**
 * Returns an array of dummy paths to run a test.
 */
function block_exclude_pages_debug_dummy_path() {
  return [
    '/node/28',
    '/node/2',
    '/user',
    '/other',
    '/user/mc',
    '/user/jc',
    '/user/jc/profile',
    '/user/jc/profile/1',
    '/user/jc/profile/mc',
    '/user/jc/settings/mc',
    '/offices/human-resources/current-employees',
    '/offices/human-resources/current-employees/manager-documents',
    '/offices/human-resources/current-employees/manager-resources',
  ];
}

/**
 * Doc function returns a string with a list of paths to check.
 */
function block_exclude_pages_debug_check() {
  $scenario = [
    'request_path' => [
      'pages' => <<<EEE
        /node/28
        !/node/2
        /user
        /user/*
        !/user/jc
        !/user/jc/*
        !/user/jc/*/mc
        /offices/human-resources/current-employees/*
        !/offices/human-resources/current-employees/manager-resources
      EEE,
    ],
  ];
  return $scenario;
}
