name: ucsf-btc-labs
recipe: pantheon
config:
  framework: drupal9
  site: ucsf-btc-labs
  id: d82a8cbf-614d-4141-b135-d388cd8cded8
  drupal: true
  webroot: .
  php: '8.3'
services:
  node:
    type: node
    build:
      - npm install
      - npm install gulp
      - gulp
    globals:
      gulp-cli: latest
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
