editor.editor.*.third_party.editor_file:
  type: mapping
  label: 'Editor File upload settings'
  mapping:
    status:
      type: boolean
      label: 'Status'
    scheme:
      type: string
      label: 'File storage'
    directory:
      type: string
      label: 'Upload directory'
    extensions:
      type: string
      label: 'Allowed file extensions'
    max_size:
      type: string
      label: 'Maximum file size'

# Plugin \Drupal\editor_file\Plugin\CKEditor5Plugin\File
ckeditor5.plugin.editor_file_file:
  type: mapping
  label: 'Editor file'
  mapping:
    status:
      type: boolean
      label: 'Status'
    scheme:
      type: string
      label: 'Scheme'
    directory:
      type: string
      label: 'Directory'
    extensions:
      type: string
      label: 'Extensions'
    max_size:
      type: string
      label: 'Maximum size'
